# DS3000 Day 1

Sept. 9, 2025

Admin
- Modules to install today `pip install collections seaborn numpy pandas` (you may not *need* to do all these, but why not?)
or `pip3 install collections seaborn numpy pandas`
  - If you don't have python and a way to edit jupyter notebooks, now's the time!
- Homework 1 due this Friday, Sept. 12 before midnight. **EC Dealine** Wednesday at 11:59 PM
- Getting to know you Due on Fri., Sep 12th [Link](https://forms.gle/25EiBnKUVgsU9Rta7)

Push-Up Tracker
- Section 03: 0
- Section 04: 0
- Section 05: 0

Content
- pandas
    - series
    - dataframe
- APIs

# Pandas


*   My nickname is Panda (Look at my cute picture)

<img src="https://images.ctfassets.net/rt5zmd3ipxai/25pHfG94sGlRALOqbRvSxl/9f591d8263607fdf923b962cbfcde2a9/NVA-panda.jpg" width=700 />


Pandas is a python module which stores data.  

### If we already have `np.array()`, why do we need pandas?
- pandas supports non numeric data (strings for categorical data, for example)
- pandas supports reading / storing data from more formats
    - csv (spreadsheets)
- pandas more elegantly deals with missing data
- pandas handles indexing woes

You could do almost everything pandas does with numpy arrays ... but it would be much more difficult to accomplish.

### Pandas has two essential objects:
- **dataframe**
    - 2 dimensional data structure
    - you've already seen one today!  (we replicate below)
- **series (vectors)**
    - 1 dimensional data structure, each item associated with some index
    - you could store the weight of all the penguins as a series
        - (all samples of one feature)
    - you could store the weight, bill size, sex, island, etc for a single penguin as a series
        - (all features for one sample)

In [1]:
import seaborn as sns

# df stands for dataframe.  df_penguin is a dataframe of penguin data
df_penguin = sns.load_dataset('penguins')
df_penguin.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Pandas Series
### building:
- building: default index
- building: custom index
- building: from a dict

In [2]:
# each row, or column is a series object
# this represents first row of dataframe
penguin0_series = df_penguin.iloc[0, :]
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
Name: 0, dtype: object

Pandas series contain a sequence of labelled data elements:
- penguin0's `species` is `Adelie`
- penguin0's `island` is `Torgersen`
- penguin0's `bill_length_mm` is `39.1` ...
- penguin0's `<index-name>` is `<corresponding-value>`

A series is quite similar to a dictionary ...

In [3]:
penguin0_dict = {'species': 'Adelie',
 'island': 'Torgersen',
 'bill_length_mm': 39.1,
 'bill_depth_mm': 18.7,
 'flipper_length_mm': 181.0,
 'body_mass_g': 3750.0,
 'sex': 'Male'}

In [4]:
import pandas as pd

# build a series from dict
penguin0_series = pd.Series(penguin0_dict)
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
dtype: object

In [5]:
# you can also pass two corresponding lists / tuples
index = ['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex']
values = ['Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'Male']

penguin0_series = pd.Series(values, index=index)
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
dtype: object

In [6]:
# you can access values via .values
penguin0_series.values

array(['Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'Male'],
      dtype=object)

In [7]:
# you can access index via .index
penguin0_series.index

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

### Using Series (hey, don't they look a little like dictionaries?)
- casting dictionaries to series
- accessing custom index:
    - by name: `series.loc[name]`
    - by position: `series.iloc[idx]`
- iterating: keys, items, iteritems (much like dict)
- deleting an entry

## There are two ways using iloc and loc:

- loc gets rows (and/or columns) with particular labels.
- iloc gets rows (and/or columns) at integer locations.

s = pd.Series(list("abcdef"), index=[49, 48, 47, 0, 1, 2]) 

49    a

48    b

47    c

0     d

1     e

2     f

s.loc[0]    # value at index label 0
'd'

s.iloc[0]   # value at index location 0
'a'

s.loc[0:1]  # rows at index labels between 0 and 1 (inclusive)
0    d
1    e

s.iloc[0:1] # rows at index location between 0 and 1 (exclusive)
49    a

In [20]:
dict_fav_num = {'mohit':  17, 'qi': 7, 'lynne': 3, 'tamrat': 1}
series_fav_num = pd.Series(dict_fav_num)
series_fav_num

mohit     17
qi         7
lynne      3
tamrat     1
dtype: int64

In [21]:
# lookup value associated with index='mohit'
series_fav_num['mohit']

np.int64(17)

In [23]:
# another way to lookup value associated with index='mohit'
series_fav_num.loc['mohit']

np.int64(17)

In [ ]:
# return the value in position 2 (the third position, from top)
series_fav_num.iloc[1]

7

In [ ]:
# each of these access methods can also set the value
series_fav_num.iloc[2] = 1000
series_fav_num

eric        17
qi           7
lynne     1000
tamrat       1
dtype: int64

## Pandas: DataFrame

Remember:
- `Series`:  1d data object
- `DataFrame`: 2d data object

`DataFrame`s represent two-dimensional data, for example, grades:

|           | Quiz 0 | Quiz 1 | Quiz 2 |
|-----------|--------|--------|--------|
| Student 0 | 80     | 90     | 50     |
| Student 1 | 87     | 92     | 80     |

Each column or row above could be considered a `Series` object (as we'll see later, we can indeed extract a single row or column of a dataframe as a `Series` object).

In [1]:
import pandas as pd
import numpy as np

quiz_array = np.array([[80, 90, 50],
                 [87, 92, 80]])

df_quiz = pd.DataFrame(quiz_array,
                       columns=('quiz0', 'quiz1', 'quiz2'),
                       index=('student0', 'student1'))
df_quiz

          quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# we construct a dataframe as a dictionary
# keys of the dictionary are columns of dataframe
# values are lists (or tuples) of the values in each column
quiz_dict = {'quiz0': [80, 87],
            'quiz1': [90, 92],
            'quiz2': [50, 80]}
pd.DataFrame(quiz_dict, index=('student0', 'student1'))

          quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# could also use .transpose() or even .T
df_quiz.transpose()
# df_quiz.T

       student0  student1
quiz0        80        87
quiz1        90        92
quiz2        50        80

## Indexing / Accessing a DataFrame
- indexing:
    - `.loc[]` indexing by name of row or column
    - `.iloc[]` indexing by position integer (0, 1, 2, 3, 4 ...)
    & slicing & subsets
- using `:` to get full rows or columns
- single cell's contents: `at`, `iat` & slicing

In [ ]:
df_quiz

          quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# indexing data by "name"
# remember: rows first, then columns ...
# 1st entry describes which row ('student0')
# 2nd entry describes which col ('quiz0')

df_quiz.loc['student0', 'quiz0']

80

In [ ]:
# index data by position
# 1st entry describes which row.  0 -> the 1st (topmost) row
# 2nd entry describes which col.  2 -> the 3rd (from the left) col
df_quiz.iloc[0, 2]

50

In [ ]:
# you can use same slicing syntaxes on both .loc and .iloc
# 1st row, last col
df_quiz.iloc[0, -1]

50

In [ ]:
# all rows, only the second col
df_quiz.iloc[:, 1]

student0    90
student1    92
Name: quiz1, dtype: int32

In [ ]:
# all rows, only quiz0
df_quiz.loc[:, 'quiz0']

student0    80
student1    87
Name: quiz0, dtype: int32

In [ ]:
# slicing with named cols and rows
# you can get a range, by name of row/col
# note: this includes both start and stop columns
df_quiz.loc['student0', 'quiz0':'quiz2' ]

quiz0    80
quiz1    90
quiz2    50
Name: student0, dtype: int32

In [ ]:
# watch out:
# when you get ranges indexed by position: include start idx, exclude stop idx)
df_quiz.iloc[0, 0:2 ]

quiz0    80
quiz1    90
Name: student0, dtype: int32

In [ ]:
# if you access directly into dataframe, it will assume you're looking for a column
# (below is equivilent to df_quiz.loc[:, 'quiz0'])
df_quiz['quiz0']

student0    80
student1    87
Name: quiz0, dtype: int32

loc gets rows (and/or columns) with particular labels.

iloc gets rows (and/or columns) at integer locations.

Additionally, `s.loc[0:2]`  # rows at index labels between 0 and 1 (inclusive) so this means 0, 1 and 2
`s.iloc[0:2]`  # rows at index labels between 0 and 1 (exclusive), so that means 0th and 1st


<img src='https://media1.giphy.com/media/l2R01mSIsazqNQ7ks/giphy.gif?cid=6c09b952x9z29ab4af9xpluk4vjxwzu6tm0nacgw1qxi8e5f&ep=v1_gifs_search&rid=giphy.gif&ct=g' width=700 />

## Modifying a DataFrame
- updating values: single cell
- adding a new column
- `pd.DataFrame.append()` and `pd.DataFrame.concat()`
    - adds a single row to a dataframe
    - `.append()` is deprecated, and may not work depending on your version of Python! Has been replaced with `.concat()` (which we use here)

In [26]:
# setting single entry in dataframe
df_quiz.loc['student0', 'quiz1'] = 123
df_quiz

          quiz0  quiz1  quiz2
student0     80    123     50
student1     87     92     80

In [27]:
# adding a new column (which student got which grade?)
# notice data frames can include columns of multiple types!
df_quiz['overall grade'] = 'a', 'b'
df_quiz

          quiz0  quiz1  quiz2 overall grade
student0     80    123     50             a
student1     87     92     80             b

In [28]:
# delete a column
del df_quiz['overall grade']
df_quiz

# There is another way of deleteing a coloumn which is by using the drop()
# function df.drop('column_name', axis=1)

          quiz0  quiz1  quiz2
student0     80    123     50
student1     87     92     80

In [30]:
# adding a column (next 2 cells) more error robust way of handling indexing
# by explicitly labelling the index we're sure to match more explicitly
s_overgrade = pd.Series({'student1': 'b-',
                         # 'student0': 'a+',
                        'student2': 'f (no quizzes taken)'})
s_overgrade

student1                      b-
student2    f (no quizzes taken)
dtype: object

In [31]:
# notice how pandas helps us out in aligning our new column with proper row
# (and avoids including student2)
df_quiz['overall grade'] = s_overgrade
df_quiz

          quiz0  quiz1  quiz2 overall grade
student0     80    123     50           NaN
student1     87     92     80            b-

In [ ]:
# how to 'drop' a row (returns a dataframe with row removed)
df_quiz_short = df_quiz.drop('student0')
df_quiz_short

          quiz0  quiz1  quiz2 overall grade
student1     87     92     80            b-

In [ ]:
# rebuild df_quiz
quiz_dict = {'quiz0': [80, 87],
            'quiz1': [90, 92],
            'quiz2': [50, 80]}
df_quiz = pd.DataFrame(quiz_dict, index=('student0', 'student1'))
df_quiz

          quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# Do you think that name thing will work for this example:
quiz_dict = {'quiz0': [80, 87],
            'quiz1': [90, 92],
            'quiz2': [50, 80]}
df_quiz = pd.DataFrame(quiz_dict, index=('student0', 'student1'),name="Student")
df_quiz

          quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

pd.series have some more parameters : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

pd.dataframe: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

In [ ]:
# add new row to dataframe
pd.concat([df_quiz, s_student3.to_frame().T])

          quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student3     95     90    100

In [ ]:
# also notice: .concat() returns a copy of df_quiz, it isn't modified above
df_quiz

          quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [ ]:
# thus, must overwrite:
df_quiz = pd.concat([df_quiz, s_student3.to_frame().T])
df_quiz

          quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student3     95     90    100

In [ ]:
# adding a column that is a function of other columns:
df_quiz['average'] = (df_quiz['quiz0'] + df_quiz.quiz1 + df_quiz.quiz2)/3
df_quiz

          quiz0  quiz1  quiz2    average
student0     80     90     50  73.333333
student1     87     92     80  86.333333
student3     95     90    100  95.000000

In [ ]:
df_quiz.average

student0    73.333333
student1    86.333333
student3    95.000000
Name: average, dtype: float64

### Boolean Indexing into DataFrame

Sometimes we want to grab only the rows or columns which meet a particular condition.

"Get all students whose grade was higher than 85 on quiz 1"

In [5]:
quiz_dict = {'quiz0': [80, 87, 60, 30],
            'quiz1': [90, 92, 60, 23],
            'quiz2': [50, 80, 70, 64]}
df_quiz = pd.DataFrame(quiz_dict, index=('student0', 'student1', 'student2', 'student3'))
df_quiz

          quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student2     60     60     70
student3     30     23     64

In [6]:
# we can build more complex conditions using
# & (and operator)
# | (or operator)

# all students who got at least an 80 on quiz1 but scored less than 75 on quiz2
s_bool = (df_quiz.loc[:, 'quiz1'] >= 80) & (df_quiz.quiz2  < 75)
s_bool

student0     True
student1    False
student2    False
student3    False
dtype: bool

In [7]:
df_quiz.loc[s_bool, :]

          quiz0  quiz1  quiz2
student0     80     90     50

# Loading Data into Pandas

Data comes from many places:
- Web Scraping
- Application Program Interface (API)
- SQL
- local file:
    - csv
    - JSON
    - fixed width tables (HTML)
    
### Pandas functions which load data
| Mode | Description
| ------ | :------
| **`read_csv`** | Load comma seperated values data from a file or URL (other delimeters too!)
| **`read_xlsx`** | Read data in xls format (Mircosoft Excel)
| **`read-fwf`** | Read data in fixed-width column format (i.e., no delimiters such as tab-separated txt files)
| **`read_clipboard`** | Version of read_csv that reads data from the clipboard; useful for converting tables from web pages
| **`read_html`** | Read all tables contained in the given HTML document.
| **`read_json`** | Read data from a JSON (JavaScript Object Notation) string representation

## Reading CSV into Pandas
- read_csv
- index_col
- header

In [6]:
import pandas as pd
# note: file must be in same folder as jupyter notebook
pd.read_csv('day-1dataset.csv')

,Restaurant,Latitude,Longitude,Address,PlaceID,URL,AverageExposure,Stars,ZIP,Count,...,HED,Unemployment,HUne,Wealth,HWe,Attraction,Hotspot,Reviews,Amenities,Amenity_Count
0,61Sliders,61.149140,-149.878090,"7920 King St, Anchorage, AK 99518",-,/biz/61sliders-anchorage?osq=Restaurants,0.124478,3.6,99507,22,...,0,4.7,1,88485,0,1,0,1,Classy,1
1,907 Alehouse & Grill,61.148140,-149.863132,"8001 Old Seward Hwy, Anchorage, AK 99518, Unit...",ChIJsX90-NaZyFYRGJ_WD0iQlaA,/biz/907-alehouse-and-grill-anchorage?osq=Rest...,0.130601,3.4,99503,93,...,0,7.9,1,63338,0,0,1,135,Takes Reservations\nOffers Takeout\nNo Deliver...,22
2,907 Wingman,61.188415,-149.907983,"3505 Spenard Rd, Anchorage, AK 99503, United S...",ChIJ4-dvWd2XyFYR-dL2s0DiD_0,/biz/907-wingman-anchorage?osq=Restaurants,0.109058,4.1,99508,9,...,0,6.5,1,65430,0,1,1,110,Offers Delivery\nOffers Takeout\nNo Reservatio...,17
3,AK Alchemist,61.218773,-149.882808,"103 E 4th Ave, Anchorage, AK 99501, United States",ChIJt_B88yiWyFYRZQB7I68Jokk,/biz/ak-alchemist-anchorage?osq=Restaurants,0.164824,3.8,99501,58,...,0,7.2,1,61509,0,1,1,178,Offers Delivery\nOffers Takeout\nNo Reservatio...,3
4,Alaska Crepery,61.217756,-149.888169,"319 W 5th Ave, Anchorage, AK 99501, United States",ChIJC6dwVAyXyFYR0ZZMmzzULww,/biz/alaska-crepery-anchorage-2?osq=Restaurants,0.161754,4.5,99507,22,...,0,4.7,1,88485,0,1,1,164,Takes Reservations\nOffers Delivery\nOffers Ta...,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,Yakishabu Sushi House,61.144031,-149.892769,"720 W Dimond Blvd, Anchorage, AK 99515, United...",ChIJMdQzoAOZyFYR1rEIFO_2Wyo,/biz/yakishabu-sushi-house-anchorage-4?osq=Res...,0.184925,3.9,99515,39,...,1,4.0,1,106755,1,0,0,32,"Offers Delivery\nOffers Takeout\nCasual, Trend...",9
287,Yamaya Seafood Restaurant,61.216698,-149.898625,"825 W 6th Ave, Anchorage, AK 99501, United States",ChIJVVN224C9yFYRmmjSJ1vPVj4,/biz/yamaya-seafood-restaurant-anchorage?osq=R...,0.123558,3.7,99501,58,...,0,7.2,1,61509,0,1,1,124,Takes Reservations\nOffers Takeout\nNo Deliver...,15
288,Yogo Delight,61.184160,-149.867577,"4007 Old Seward Hwy # 200, Anchorage, AK 99503...",ChIJT0w0d7yXyFYRcCATvyPkT6Y,/biz/yogo-delight-anchorage?osq=Restaurants,0.099800,4.4,99508,9,...,0,6.5,1,65430,0,1,0,116,Offers Takeout\nNo Reservations\nNo Delivery\n...,18
289,Zorba's Gyros,61.195857,-149.890254,"2700 Blueberry Rd, Anchorage, AK 99503, United...",ChIJI7cNe8WXyFYRuJw8-CPA5f4,/biz/zorbas-gyros-anchorage?osq=Restaurants,0.116808,4.4,99518,21,...,0,3.0,0,84045,0,1,1,80,Offers Takeout\nNo Reservations\nAccepts Credi...,11
290,Serrano's Mexican Grill,61.195468,-149.880141,"201 E Northern Lights Blvd, Anchorage, AK 9950...",ChIJH0A8uciXyFYRQvUedUNWEEU,/biz/serranos-mexican-grill-anchorage?osq=Rest...,0.141745,3.9,99577,13,...,1,3.5,1,111388,1,1,0,270,Offers Delivery\nOffers Takeout\nNo Reservatio...,20

In [8]:
# look at the first few rows (header)
gtky = pd.read_csv('day-1dataset.csv', index_col='Latitude')
gtky.head()

,Restaurant,Longitude,Address,PlaceID,URL,AverageExposure,Stars,ZIP,Count,White,...,HED,Unemployment,HUne,Wealth,HWe,Attraction,Hotspot,Reviews,Amenities,Amenity_Count
Latitude,,,,,,,,,,,,,,,,,,,,,
61.149140,61Sliders,-149.878090,"7920 King St, Anchorage, AK 99518",-,/biz/61sliders-anchorage?osq=Restaurants,0.124478,3.6,99507,22,20110,...,0,4.7,1,88485,0,1,0,1,Classy,1
61.148140,907 Alehouse & Grill,-149.863132,"8001 Old Seward Hwy, Anchorage, AK 99518, Unit...",ChIJsX90-NaZyFYRGJ_WD0iQlaA,/biz/907-alehouse-and-grill-anchorage?osq=Rest...,0.130601,3.4,99503,93,6167,...,0,7.9,1,63338,0,0,1,135,Takes Reservations\nOffers Takeout\nNo Deliver...,22
61.188415,907 Wingman,-149.907983,"3505 Spenard Rd, Anchorage, AK 99503, United S...",ChIJ4-dvWd2XyFYR-dL2s0DiD_0,/biz/907-wingman-anchorage?osq=Restaurants,0.109058,4.1,99508,9,15722,...,0,6.5,1,65430,0,1,1,110,Offers Delivery\nOffers Takeout\nNo Reservatio...,17
61.218773,AK Alchemist,-149.882808,"103 E 4th Ave, Anchorage, AK 99501, United States",ChIJt_B88yiWyFYRZQB7I68Jokk,/biz/ak-alchemist-anchorage?osq=Restaurants,0.164824,3.8,99501,58,9223,...,0,7.2,1,61509,0,1,1,178,Offers Delivery\nOffers Takeout\nNo Reservatio...,3
61.217756,Alaska Crepery,-149.888169,"319 W 5th Ave, Anchorage, AK 99501, United States",ChIJC6dwVAyXyFYR0ZZMmzzULww,/biz/alaska-crepery-anchorage-2?osq=Restaurants,0.161754,4.5,99507,22,20110,...,0,4.7,1,88485,0,1,1,164,Takes Reservations\nOffers Delivery\nOffers Ta...,16

In [10]:
# look at stats for the different classes
class_gtky = gtky.groupby("ZIP")
class_gtky.describe()

      Longitude                                                            \
          count        mean       std         min         25%         50%
ZIP
99501      56.0 -148.742000  8.439060 -149.982134 -149.896281 -149.888814
99502       6.0 -149.916733  0.045542 -149.983585 -149.943912 -149.912612
99503      94.0 -149.874413  0.058371 -149.952618 -149.904025 -149.885408
99504      10.0 -149.618327  0.699157 -149.915430 -149.890578 -149.836955
99507      23.0 -149.867175  0.043462 -149.913815 -149.893826 -149.885075
99508       9.0 -149.851966  0.054903 -149.907983 -149.890611 -149.867577
99515      39.0 -149.843831  0.090286 -149.915729 -149.893782 -149.874919
99517      15.0 -149.865809  0.090081 -149.937970 -149.915144 -149.892066
99518      21.0 -149.876652  0.074823 -149.942590 -149.897319 -149.890254
99540       4.0 -149.694135  0.216026 -149.893939 -149.874339 -149.692308
99577      14.0 -147.550504  8.720974 -149.982857 -149.892293 -149.873930

                              AverageExposure            ... Reviews          \
              75%         max           count      mean  ...     75%     max
ZIP                                                      ...
99501 -149.872529  -86.719709            56.0  0.153591  ...  230.25  2480.0
99502 -149.882729 -149.864476             6.0  0.115208  ...   70.00   155.0
99503 -149.868873 -149.563550            94.0  0.133839  ...  162.75  2967.0
99504 -149.766768 -147.636225            10.0  0.122940  ...  126.50   414.0
99507 -149.857953 -149.741059            23.0  0.105630  ...  198.00   426.0
99508 -149.839750 -149.734193             9.0  0.118777  ...  167.00   226.0
99515 -149.836392 -149.568249            39.0  0.110079  ...  135.50   607.0
99517 -149.861268 -149.570695            15.0  0.128230  ...  160.00   486.0
99518 -149.867133 -149.569488            21.0  0.121858  ...  141.00   358.0
99540 -149.512104 -149.497986             4.0  0.203595  ...   84.75   102.0
99577 -149.843747 -117.250918            14.0  0.103617  ...  190.00   270.0

      Amenity_Count
              count       mean       std   min    25%   50%    75%   max
ZIP
99501          56.0   8.285714  7.300596   2.0   3.00   4.0  14.25  27.0
99502           6.0  14.333333  3.983298  11.0  11.25  13.0  16.25  21.0
99503          94.0  13.361702  7.029662   0.0   9.00  14.0  17.00  31.0
99504          10.0  12.900000  7.125073   2.0   7.25  13.5  16.75  25.0
99507          23.0   6.434783  7.011848   0.0   2.00   4.0   8.50  23.0
99508           9.0  17.444444  6.710274   3.0  17.00  18.0  19.00  29.0
99515          39.0  12.435897  6.443254   0.0   8.00  14.0  16.00  32.0
99517          15.0  13.466667  5.755329   3.0  10.00  14.0  17.50  24.0
99518          21.0  15.380952  5.074211   5.0  12.00  16.0  19.00  27.0
99540           4.0  16.000000  4.320494  10.0  14.50  17.0  18.50  20.0
99577          14.0  14.500000  6.560371   2.0  11.50  15.5  18.75  25.0

[11 rows x 248 columns]

## Saving a DataFrame as a csv
- .to_csv()
- index=False
- header=False
- appending to csv (mode='a', header=None)

# Extra Credit Task 1

## Create code for the following questions and run the cells. If there are errors you need to discuss in the markdown cell why a particular cell did not work. Before submitting delete all the other cells!

Using the Titanic dataset do the following questions: 

a) Using iloc obtain all rows but only last 3 columns of the dataset

b) Using loc obtain all rows, but only last 2 coloumns of the dataset

c) Using boolean indexing, obtain all the rows where `fare` > 10.3

In [35]:
import seaborn as sns
import pandas as pd

titan = sns.load_dataset('titanic')

In [ ]:
#a

In [ ]:
#b

In [ ]:
#c

# API
###  Definitions
**API** Application Program Interface
 - a server which gives out data (often over the internet)
 - note: 'API', in general, refers to the barrier between two pieces of software:
     - in this case, the server which hosts data & our own software which requests it

 **JSON** JavaScript Object Notation
  - a method of storing objects as text
  - much like the nested dictionaries ... JSON and similar formats are often trees

## OpenWeather API
What information does this offer?

[https://openweathermap.org/api](https://openweathermap.org/api)

How do I get ready to use it?
- sign up for an account
    - [https://home.openweathermap.org/users/sign_up](https://home.openweathermap.org/users/sign_up)
- get an api key (my key was emailed to me with my confirmation of account)
    - [https://home.openweathermap.org/api_keys](https://home.openweathermap.org/api_keys)
 
![ap](https://www.memecreator.org/static/images/memes/4593014.jpg)
        
Think of APIs as a hybrid of a website and a function.  Its a website where your query is stored in the address:
    
    https://api.openweathermap.org/data/3.0/onecall?lat=42.3601&lon=-71.0589&appid=YOUR-API-KEY-HERE-THIS-WONT-WORK&units=imperial
    
The result is a JSON object, which we can quickly convert to our dictionary of dictionary tree format.

In [2]:
# todo: swap this out
api_key = 'cf758020c3c57082bbfd8b62d88ca683'

# north = positive, south = negative
lat = 50.8823
# east = positive, west = negative
lon = 4.7138

# could use metric if you're feeling very European
units = 'metric'
url = f'https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&appid={api_key}&units={units}'
print(url)

https://api.openweathermap.org/data/3.0/onecall?lat=50.8823&lon=4.7138&appid=cf758020c3c57082bbfd8b62d88ca683&units=metric

In [3]:
import requests

# get url as a string
url_text = requests.get(url).text    
url_text

'{"lat":50.8823,"lon":4.7138,"timezone":"Europe/Brussels","timezone_offset":7200,"current":{"dt":1752006918,"sunrise":1751945830,"sunset":1752004493,"temp":15.73,"feels_like":15.24,"pressure":1019,"humidity":72,"dew_point":10.7,"uvi":0,"clouds":100,"visibility":10000,"wind_speed":4.63,"wind_deg":320,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}]},"minutely":[{"dt":1752006960,"precipitation":0},{"dt":1752007020,"precipitation":0},{"dt":1752007080,"precipitation":0},{"dt":1752007140,"precipitation":0},{"dt":1752007200,"precipitation":0},{"dt":1752007260,"precipitation":0},{"dt":1752007320,"precipitation":0},{"dt":1752007380,"precipitation":0},{"dt":1752007440,"precipitation":0},{"dt":1752007500,"precipitation":0},{"dt":1752007560,"precipitation":0},{"dt":1752007620,"precipitation":0},{"dt":1752007680,"precipitation":0},{"dt":1752007740,"precipitation":0},{"dt":1752007800,"precipitation":0},{"dt":1752007860,"precipitation":0},{"dt":1752007920,"precipitation":0},{"dt":1752007980,"precipitation":0},{"dt":1752008040,"precipitation":0},{"dt":1752008100,"precipitation":0},{"dt":1752008160,"precipitation":0},{"dt":1752008220,"precipitation":0},{"dt":1752008280,"precipitation":0},{"dt":1752008340,"precipitation":0},{"dt":1752008400,"precipitation":0},{"dt":1752008460,"precipitation":0},{"dt":1752008520,"precipitation":0},{"dt":1752008580,"precipitation":0},{"dt":1752008640,"precipitation":0},{"dt":1752008700,"precipitation":0},{"dt":1752008760,"precipitation":0},{"dt":1752008820,"precipitation":0},{"dt":1752008880,"precipitation":0},{"dt":1752008940,"precipitation":0},{"dt":1752009000,"precipitation":0},{"dt":1752009060,"precipitation":0},{"dt":1752009120,"precipitation":0},{"dt":1752009180,"precipitation":0},{"dt":1752009240,"precipitation":0},{"dt":1752009300,"precipitation":0},{"dt":1752009360,"precipitation":0},{"dt":1752009420,"precipitation":0},{"dt":1752009480,"precipitation":0},{"dt":1752009540,"precipitation":0},{"dt":1752009600,"precipitation":0},{"dt":1752009660,"precipitation":0},{"dt":1752009720,"precipitation":0},{"dt":1752009780,"precipitation":0},{"dt":1752009840,"precipitation":0},{"dt":1752009900,"precipitation":0},{"dt":1752009960,"precipitation":0},{"dt":1752010020,"precipitation":0},{"dt":1752010080,"precipitation":0},{"dt":1752010140,"precipitation":0},{"dt":1752010200,"precipitation":0},{"dt":1752010260,"precipitation":0},{"dt":1752010320,"precipitation":0},{"dt":1752010380,"precipitation":0},{"dt":1752010440,"precipitation":0},{"dt":1752010500,"precipitation":0}],"hourly":[{"dt":1752004800,"temp":15.71,"feels_like":15.24,"pressure":1019,"humidity":73,"dew_point":10.89,"uvi":0,"clouds":80,"visibility":10000,"wind_speed":3.38,"wind_deg":292,"wind_gust":6.01,"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],"pop":0},{"dt":1752008400,"temp":15.73,"feels_like":15.24,"pressure":1019,"humidity":72,"dew_point":10.7,"uvi":0,"clouds":100,"visibility":10000,"wind_speed":3.46,"wind_deg":285,"wind_gust":6.7,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"pop":0},{"dt":1752012000,"temp":15.49,"feels_like":15.03,"pressure":1019,"humidity":74,"dew_point":10.88,"uvi":0,"clouds":82,"visibility":10000,"wind_speed":3.2,"wind_deg":281,"wind_gust":6,"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],"pop":0},{"dt":1752015600,"temp":15.07,"feels_like":14.64,"pressure":1019,"humidity":77,"dew_point":11.07,"uvi":0,"clouds":68,"visibility":10000,"wind_speed":3.11,"wind_deg":273,"wind_gust":5.14,"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],"pop":0},{"dt":1752019200,"temp":14.47,"feels_like":14.09,"pressure":1020,"humidity":81,"dew_point":11.25,"uvi":0,"clouds":51,"visibility":10000,"wind_speed":2.83,"wind_deg":260,"wind_gust":3.69,"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],"pop":0},{"dt":1752022800,"temp":14.04,"feels_like":13.69,"pressure":1020,"humidity":84,"dew_point":11.38,"uvi":0,"clouds":100,"visibility":10000,"wind_speed":2.64,"wind_deg":250,"wind_gust":2.91,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"pop":0},{"dt":1752026400,"temp":12.47,"feels_like":12.12,"pressure":1020,"humidity":90,"dew_point":9.13,"uvi":0,"clouds":100,"visibility":10000,"wind_speed":2.93,"wind_deg":245,"wind_gust":3.8,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"pop":0},{"dt":1752030000,"temp":11.83,"feels_like":11.39,"pressure":1020,"humidity":89,"dew_point":8.83,"uvi":0,"clouds":100,"visibility":10000,"wind_speed":2.82,"wind_deg":238,"wind_gust":3.8,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"pop":0},{"dt":1752033600,"temp":11.43,"feels_like":10.93,"pressure":1020,"humidity":88,"dew_point":8.53,"uvi":0,"clouds":100,"visibility":10000,"wind_speed":2.98,"wind_deg":232,"wind_gust":4.79,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"pop":0},{"dt":1752037200,"temp":12.51,"feels_like":12.01,"pressure":1021,"humidity":84,"dew_point":8.72,"uvi":0.25,"clouds":93,"visibility":10000,"wind_speed":2.55,"wind_deg":232,"wind_gust":4.77,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"pop":0},{"dt":1752040800,"temp":14.28,"feels_like":13.72,"pressure":1021,"humidity":75,"dew_point":9.23,"uvi":0.75,"clouds":86,"visibility":10000,"wind_speed":2.72,"wind_deg":253,"wind_gust":3.64,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"pop":0},{"dt":1752044400,"temp":16.2,"feels_like":15.73,"pressure":1021,"humidity":71,"dew_point":10.38,"uvi":1.62,"clouds":51,"visibility":10000,"wind_speed":2.69,"wind_deg":266,"wind_gust":3.43,"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],"pop":0},{"dt":1752048000,"temp":18.4,"feels_like":17.99,"pressure":1021,"humidity":65,"dew_point":10.95,"uvi":3,"clouds":52,"visibility":10000,"wind_speed":2.9,"wind_deg":273,"wind_gust":3.9,"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],"pop":0},{"dt":1752051600,"temp":19.1,"feels_like":18.4,"pressure":1021,"humidity":51,"dew_point":9.3,"uvi":4.57,"clouds":40,"visibility":10000,"wind_speed":3.18,"wind_deg":295,"wind_gust":4.39,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752055200,"temp":20.19,"feels_like":19.44,"pressure":1021,"humidity":45,"dew_point":8.57,"uvi":6.03,"clouds":38,"visibility":10000,"wind_speed":3.4,"wind_deg":303,"wind_gust":4.8,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752058800,"temp":21.32,"feels_like":20.6,"pressure":1021,"humidity":42,"dew_point":8.72,"uvi":6.96,"clouds":37,"visibility":10000,"wind_speed":3.54,"wind_deg":306,"wind_gust":4.88,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752062400,"temp":23.94,"feels_like":23.41,"pressure":1021,"humidity":39,"dew_point":8.51,"uvi":7.17,"clouds":35,"visibility":10000,"wind_speed":3.78,"wind_deg":313,"wind_gust":4.84,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752066000,"temp":23.92,"feels_like":23.33,"pressure":1021,"humidity":37,"dew_point":8.2,"uvi":6.53,"clouds":15,"visibility":10000,"wind_speed":3.89,"wind_deg":325,"wind_gust":4.68,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752069600,"temp":24.35,"feels_like":23.75,"pressure":1021,"humidity":35,"dew_point":7.91,"uvi":5.27,"clouds":13,"visibility":10000,"wind_speed":4.02,"wind_deg":337,"wind_gust":4.56,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752073200,"temp":24.34,"feels_like":23.74,"pressure":1021,"humidity":35,"dew_point":7.8,"uvi":3.7,"clouds":13,"visibility":10000,"wind_speed":4.06,"wind_deg":347,"wind_gust":4.3,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752076800,"temp":23.99,"feels_like":23.38,"pressure":1021,"humidity":36,"dew_point":7.82,"uvi":2.21,"clouds":14,"visibility":10000,"wind_speed":4.4,"wind_deg":355,"wind_gust":4.17,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752080400,"temp":23.2,"feels_like":22.57,"pressure":1021,"humidity":38,"dew_point":7.93,"uvi":1.09,"clouds":12,"visibility":10000,"wind_speed":4.53,"wind_deg":1,"wind_gust":3.83,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752084000,"temp":21.56,"feels_like":20.95,"pressure":1021,"humidity":45,"dew_point":9.14,"uvi":0.4,"clouds":26,"visibility":10000,"wind_speed":3.96,"wind_deg":1,"wind_gust":5.86,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752087600,"temp":19.06,"feels_like":18.46,"pressure":1021,"humidity":55,"dew_point":9.6,"uvi":0.11,"clouds":42,"visibility":10000,"wind_speed":3.22,"wind_deg":1,"wind_gust":5.59,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752091200,"temp":16.71,"feels_like":15.98,"pressure":1022,"humidity":59,"dew_point":8.51,"uvi":0,"clouds":30,"visibility":10000,"wind_speed":3.02,"wind_deg":8,"wind_gust":3.41,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03n"}],"pop":0},{"dt":1752094800,"temp":15.51,"feels_like":14.71,"pressure":1022,"humidity":61,"dew_point":7.94,"uvi":0,"clouds":36,"visibility":10000,"wind_speed":2.49,"wind_deg":15,"wind_gust":2.46,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03n"}],"pop":0},{"dt":1752098400,"temp":14.46,"feels_like":13.58,"pressure":1023,"humidity":62,"dew_point":7.17,"uvi":0,"clouds":30,"visibility":10000,"wind_speed":2.06,"wind_deg":23,"wind_gust":2.06,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03n"}],"pop":0},{"dt":1752102000,"temp":13.58,"feels_like":12.61,"pressure":1023,"humidity":62,"dew_point":6.48,"uvi":0,"clouds":27,"visibility":10000,"wind_speed":1.78,"wind_deg":32,"wind_gust":1.83,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03n"}],"pop":0},{"dt":1752105600,"temp":12.82,"feels_like":11.8,"pressure":1023,"humidity":63,"dew_point":5.85,"uvi":0,"clouds":25,"visibility":10000,"wind_speed":1.45,"wind_deg":64,"wind_gust":1.44,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03n"}],"pop":0},{"dt":1752109200,"temp":12.45,"feels_like":11.4,"pressure":1023,"humidity":63,"dew_point":5.41,"uvi":0,"clouds":15,"visibility":10000,"wind_speed":1.22,"wind_deg":99,"wind_gust":1.23,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02n"}],"pop":0},{"dt":1752112800,"temp":12.13,"feels_like":11.04,"pressure":1023,"humidity":63,"dew_point":5.22,"uvi":0,"clouds":13,"visibility":10000,"wind_speed":0.92,"wind_deg":121,"wind_gust":0.91,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02n"}],"pop":0},{"dt":1752116400,"temp":12.02,"feels_like":10.92,"pressure":1023,"humidity":63,"dew_point":5.08,"uvi":0,"clouds":12,"visibility":10000,"wind_speed":0.62,"wind_deg":136,"wind_gust":0.57,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02n"}],"pop":0},{"dt":1752120000,"temp":11.95,"feels_like":10.87,"pressure":1023,"humidity":64,"dew_point":5.24,"uvi":0,"clouds":20,"visibility":10000,"wind_speed":0.38,"wind_deg":112,"wind_gust":0.38,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752123600,"temp":13.69,"feels_like":12.76,"pressure":1023,"humidity":63,"dew_point":6.78,"uvi":0.26,"clouds":25,"visibility":10000,"wind_speed":0.48,"wind_deg":77,"wind_gust":0.43,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752127200,"temp":15.88,"feels_like":14.96,"pressure":1023,"humidity":55,"dew_point":6.86,"uvi":0.78,"clouds":23,"visibility":10000,"wind_speed":0.76,"wind_deg":57,"wind_gust":0.77,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752130800,"temp":18.05,"feels_like":17.24,"pressure":1023,"humidity":51,"dew_point":7.71,"uvi":1.35,"clouds":10,"visibility":10000,"wind_speed":0.84,"wind_deg":27,"wind_gust":1.02,"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"pop":0},{"dt":1752134400,"temp":19.79,"feels_like":19.05,"pressure":1023,"humidity":47,"dew_point":8.2,"uvi":3.07,"clouds":22,"visibility":10000,"wind_speed":1.5,"wind_deg":4,"wind_gust":1.77,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752138000,"temp":21.26,"feels_like":20.62,"pressure":1023,"humidity":45,"dew_point":8.76,"uvi":4.7,"clouds":24,"visibility":10000,"wind_speed":1.9,"wind_deg":359,"wind_gust":2.3,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752141600,"temp":22.67,"feels_like":22.17,"pressure":1023,"humidity":45,"dew_point":10.04,"uvi":6.02,"clouds":33,"visibility":10000,"wind_speed":2.19,"wind_deg":355,"wind_gust":2.64,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752145200,"temp":23.78,"feels_like":23.36,"pressure":1023,"humidity":44,"dew_point":10.74,"uvi":7.01,"clouds":38,"visibility":10000,"wind_speed":2.8,"wind_deg":348,"wind_gust":3.16,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752148800,"temp":24.85,"feels_like":24.49,"pressure":1022,"humidity":42,"dew_point":10.98,"uvi":7.16,"clouds":31,"visibility":10000,"wind_speed":3.27,"wind_deg":344,"wind_gust":3.78,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"pop":0},{"dt":1752152400,"temp":25.77,"feels_like":25.42,"pressure":1022,"humidity":39,"dew_point":10.81,"uvi":6.48,"clouds":4,"visibility":10000,"wind_speed":3.62,"wind_deg":344,"wind_gust":3.99,"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"pop":0},{"dt":1752156000,"temp":26.2,"feels_like":26.2,"pressure":1022,"humidity":38,"dew_point":10.72,"uvi":5.23,"clouds":7,"visibility":10000,"wind_speed":3.91,"wind_deg":337,"wind_gust":4.26,"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"pop":0},{"dt":1752159600,"temp":26.32,"feels_like":26.32,"pressure":1021,"humidity":39,"dew_point":11.05,"uvi":3.66,"clouds":13,"visibility":10000,"wind_speed":4.62,"wind_deg":330,"wind_gust":4.64,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752163200,"temp":25.89,"feels_like":25.61,"pressure":1021,"humidity":41,"dew_point":11.51,"uvi":2.19,"clouds":15,"visibility":10000,"wind_speed":5.58,"wind_deg":330,"wind_gust":4.89,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752166800,"temp":24.97,"feels_like":24.67,"pressure":1021,"humidity":44,"dew_point":11.83,"uvi":1.08,"clouds":17,"visibility":10000,"wind_speed":5.86,"wind_deg":333,"wind_gust":5.11,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752170400,"temp":23.8,"feels_like":23.57,"pressure":1021,"humidity":51,"dew_point":12.89,"uvi":0.41,"clouds":16,"visibility":10000,"wind_speed":5.29,"wind_deg":335,"wind_gust":6.32,"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"pop":0},{"dt":1752174000,"temp":21.63,"feels_like":21.36,"pressure":1021,"humidity":58,"dew_point":12.88,"uvi":0.11,"clouds":0,"visibility":10000,"wind_speed":4.71,"wind_deg":339,"wind_gust":8.31,"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"pop":0}],"daily":[{"dt":1751972400,"sunrise":1751945830,"sunset":1752004493,"moonrise":1752000420,"moonset":1751935320,"moon_phase":0.42,"summary":"Expect a day of partly cloudy with rain","temp":{"day":18.26,"min":12.13,"max":19.04,"night":15.73,"eve":17.61,"morn":12.72},"feels_like":{"day":17.86,"night":15.24,"eve":17.1,"morn":12.45},"pressure":1015,"humidity":66,"dew_point":8.75,"wind_speed":7.73,"wind_deg":320,"wind_gust":10.83,"weather":[{"id":501,"main":"Rain","description":"moderate rain","icon":"10d"}],"clouds":55,"pop":1,"rain":6.26,"uvi":5.86},{"dt":1752058800,"sunrise":1752032287,"sunset":1752090853,"moonrise":1752090060,"moonset":1752024420,"moon_phase":0.45,"summary":"There will be partly cloudy today","temp":{"day":21.32,"min":11.43,"max":24.35,"night":15.51,"eve":23.2,"morn":12.51},"feels_like":{"day":20.6,"night":14.71,"eve":22.57,"morn":12.01},"pressure":1021,"humidity":42,"dew_point":8.72,"wind_speed":4.53,"wind_deg":1,"wind_gust":6,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"clouds":37,"pop":0,"uvi":7.17},{"dt":1752145200,"sunrise":1752118746,"sunset":1752177211,"moonrise":1752178860,"moonset":1752114300,"moon_phase":0.5,"summary":"Expect a day of partly cloudy with clear spells","temp":{"day":23.78,"min":11.95,"max":26.32,"night":17.13,"eve":24.97,"morn":13.69},"feels_like":{"day":23.36,"night":16.73,"eve":24.67,"morn":12.76},"pressure":1023,"humidity":44,"dew_point":10.74,"wind_speed":5.86,"wind_deg":333,"wind_gust":8.31,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"clouds":38,"pop":0,"uvi":7.16},{"dt":1752231600,"sunrise":1752205207,"sunset":1752263566,"moonrise":1752267060,"moonset":1752205080,"moon_phase":0.52,"summary":"The day will start with clear sky through the late morning hours, transitioning to partly cloudy","temp":{"day":24.17,"min":12.54,"max":26.23,"night":18.23,"eve":25.32,"morn":13.87},"feels_like":{"day":23.9,"night":17.96,"eve":25.06,"morn":13.58},"pressure":1020,"humidity":48,"dew_point":12.34,"wind_speed":4.89,"wind_deg":28,"wind_gust":6.2,"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"clouds":40,"pop":0,"uvi":7.22},{"dt":1752318000,"sunrise":1752291670,"sunset":1752349918,"moonrise":1752354780,"moonset":1752296220,"moon_phase":0.55,"summary":"Expect a day of partly cloudy with clear spells","temp":{"day":26.72,"min":13.73,"max":28.26,"night":18.25,"eve":24.3,"morn":17.2},"feels_like":{"day":26.36,"night":17.7,"eve":24.06,"morn":17.04},"pressure":1015,"humidity":33,"dew_point":9.15,"wind_speed":5.54,"wind_deg":306,"wind_gust":7.42,"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"clouds":5,"pop":0,"uvi":6.89},{"dt":1752404400,"sunrise":1752378135,"sunset":1752436267,"moonrise":1752442200,"moonset":1752387540,"moon_phase":0.59,"summary":"Expect a day of partly cloudy with clear spells","temp":{"day":28.65,"min":13.86,"max":29.08,"night":17.89,"eve":25.11,"morn":17.87},"feels_like":{"day":27.96,"night":17.77,"eve":24.85,"morn":17.59},"pressure":1014,"humidity":36,"dew_point":12.27,"wind_speed":6.43,"wind_deg":321,"wind_gust":5.81,"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"clouds":7,"pop":0,"uvi":6.79},{"dt":1752490800,"sunrise":1752464602,"sunset":1752522614,"moonrise":1752529440,"moonset":1752478920,"moon_phase":0.62,"summary":"You can expect clear sky in the morning, with partly cloudy in the afternoon","temp":{"day":28.44,"min":14.42,"max":30.3,"night":21.89,"eve":28.72,"morn":18.14},"feels_like":{"day":27.71,"night":21.54,"eve":28.17,"morn":17.86},"pressure":1016,"humidity":35,"dew_point":11.45,"wind_speed":2.82,"wind_deg":360,"wind_gust":3.75,"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"clouds":0,"pop":0,"uvi":7},{"dt":1752577200,"sunrise":1752551070,"sunset":1752608958,"moonrise":1752616560,"moonset":1752570180,"moon_phase":0.66,"summary":"Expect a day of partly cloudy with rain","temp":{"day":27.76,"min":17.6,"max":27.76,"night":19.57,"eve":24.69,"morn":21.68},"feels_like":{"day":28.02,"night":18.94,"eve":24.15,"

In [4]:
# should not have to install the below
import json

# convert json to a nested dict
weather_dict = json.loads(url_text)

weather_dict.keys()

dict_keys(['lat', 'lon', 'timezone', 'timezone_offset', 'current', 'minutely', 'hourly', 'daily'])

In [5]:
weather_dict['hourly'][0]

{'dt': 1752004800,
 'temp': 15.71,
 'feels_like': 15.24,
 'pressure': 1019,
 'humidity': 73,
 'dew_point': 10.89,
 'uvi': 0,
 'clouds': 80,
 'visibility': 10000,
 'wind_speed': 3.38,
 'wind_deg': 292,
 'wind_gust': 6.01,
 'weather': [{'id': 803,
   'main': 'Clouds',
   'description': 'broken clouds',
   'icon': '04n'}],
 'pop': 0}

# Extra Credit Opportunity 2

## Put a python code that does these two tasks:

1) Print the value in the `weather` key inside `hourly` key.
2) Print the value in the `description` key inside `weather` key

In [ ]:
# put your code here

## Cleaning up data from one hour

In [6]:
from datetime import datetime
import pandas as pd

hour_dict = weather_dict['hourly'][0]
hour_dict

# lets convert from unix time to a datetime (easier to use)
hour_dict['datetime'] = datetime.fromtimestamp(hour_dict['dt'])

pd.Series(hour_dict)

dt                                                   1752004800
temp                                                      15.71
feels_like                                                15.24
pressure                                                   1019
humidity                                                     73
dew_point                                                 10.89
uvi                                                           0
clouds                                                       80
visibility                                                10000
wind_speed                                                 3.38
wind_deg                                                    292
wind_gust                                                  6.01
weather       [{'id': 803, 'main': 'Clouds', 'description': ...
pop                                                           0
datetime                                    2025-07-08 16:00:00
dtype: object

# Timestamps

Many datasets include a timestamp, or include a date/time as a feature in the dataset. Understanding how to deal with these can be important! We actually already used pandas `.to_datetime()` function with the Korean Demographics data to cast strings to `datetime` objects. We'll look a few time highlights which will come in handy on Homework 2.

## Unix Time

- [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) Coordinated Universal Time
    - time zone at 0 deg longitude
        - how is 0 deg longitude defined?  
            - A succesfully warring empire (United Kingdom) chose it 
                - (It would be convenient if a metric system loving empire had been more successful at war ...)
- [Unix Time](https://en.wikipedia.org/wiki/Unix_time) is The number of seconds which have passed since 00:00:00 UTC on 1 Jan 1970 (ignoring leap seconds)
![unix](https://i.redd.it/o1li4ktbyf871.png)
- UTC is time zone agnostic 
    - (more on this next lesson...)

## Python's `datetime`, `timedelta`, and pytz
- helpful for all those pesky unit conversions

In [7]:
# use strptime to take the time from strings contain other words
datetime.strptime('the time is now: September-30-2024 9:20 PM', 'the time is now: %B-%d-%Y %H:%M %p')

datetime.datetime(2024, 9, 30, 9, 20)

In [8]:
# use strftime to cast a time to a string that contains other words
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
datetime.now().strftime('the time is now: %B-%d-%Y %H:%M %p')

'the time is now: July-08-2025 16:40 PM'

In [9]:
df_hourly = pd.DataFrame()
for hour_dict in weather_dict['hourly']:

    # lets convert from unix time to a datetime (easier to use)
    hour_dict['datetime'] = datetime.fromtimestamp(hour_dict['dt'])

    s_hour = pd.Series(hour_dict)
    
    df_hourly = pd.concat([df_hourly, s_hour.to_frame().T], ignore_index=True)
    
df_hourly.head()

,dt,temp,feels_like,pressure,humidity,dew_point,uvi,clouds,visibility,wind_speed,wind_deg,wind_gust,weather,pop,datetime
0,1752004800,15.71,15.24,1019,73,10.89,0,80,10000,3.38,292,6.01,"[{'id': 803, 'main': 'Clouds', 'description': ...",0,2025-07-08 16:00:00
1,1752008400,15.73,15.24,1019,72,10.7,0,100,10000,3.46,285,6.7,"[{'id': 804, 'main': 'Clouds', 'description': ...",0,2025-07-08 17:00:00
2,1752012000,15.49,15.03,1019,74,10.88,0,82,10000,3.2,281,6,"[{'id': 803, 'main': 'Clouds', 'description': ...",0,2025-07-08 18:00:00
3,1752015600,15.07,14.64,1019,77,11.07,0,68,10000,3.11,273,5.14,"[{'id': 803, 'main': 'Clouds', 'description': ...",0,2025-07-08 19:00:00
4,1752019200,14.47,14.09,1020,81,11.25,0,51,10000,2.83,260,3.69,"[{'id': 803, 'main': 'Clouds', 'description': ...",0,2025-07-08 20:00:00

## Extra Credit Opportunity 3

Capri, Italy is located at:

    40.5532° N, 14.2222° E


Dr. Singhal was there this summer! Here is the picture:

![f](https://www.dropbox.com/scl/fi/xzu6affw6bijn4aaf4m4q/IMG_3725.jpg?rlkey=mholpafjojr23usuz3r0pggp5&st=ouenmvvi&raw=1)

    
1. Create a dataframe of the next 48 hours of their weather as was done above
2. (++) Make a function `get_forecast` which accepts:
    - `lat`
    - `lon`
    - `api_key`
    - `units` (default = 'imperial')
    
    and returns a dataframe of the next 48 hours of the location's weather. Test it on a location of your choice.

In [ ]:
# get_forecast(40.5532, 14.2222)